CONFIG_QEMU_ICOUNT=n

CONFIG_GPIO_EMUL=y

CONFIG_PWM=y

CONFIG_LOG=y

CONFIG_BLINK_TIMER_INTERVAL=2000

CONFIG_UART_CONSOLE=y

CONFIG_ASSERT=y

CONFIG_LOG_DEFAULT_LEVEL=4
CONFIG_KERNEL_LOG_LEVEL_INF=y
